# Generated by Django 4.2.4 on 2023-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='', max_length=1)),
                ('description', models.TextField(default='', max_length=10000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1, max_length=100)),
                ('salary', models.IntegerField(default=0, max_length=6)),
                ('experience', models.IntegerField(default=0, max_length=2)),
            ],
        ),
    ]
