# Generated by Django 4.2.4 on 2023-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_experience_alter_job_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('R', 'Remote')], default='', max_length=1),
        ),
    ]
