# Generated by Django 4.2.4 on 2023-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('R', 'Remote')], max_length=1),
        ),
    ]
