# Generated by Django 4.2.4 on 2023-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_alter_job_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
