# Generated by Django 4.2.4 on 2023-08-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_job_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="job.category"
            ),
        ),
    ]
