# Generated by Django 4.2.4 on 2023-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
        ),
    ]
