# Generated by Django 4.2.4 on 2023-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/%Y/%m/%d/"),
        ),
    ]
