# Generated by Django 4.2.4 on 2023-08-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0012_apply_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apply",
                to="job.job",
            ),
        ),
    ]
